workspace:
  base: /workdir
  path: .

pipeline:

  # Caching (restore if present)
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./maven-repo
      - ./nlp-data
    volumes:
      - /tmp/cache:/cache
    when:
      event: [ push ]

  # Build and test.
  mavenBuild:
    image: meltwaterfoundation/drone-maven-jdk8
    pull: true
    secrets: [ artifactory_username, artifactory_password ]
    commands:
      - echo 'Build and test.'
      - mvn -U clean install -s settings.xml
    when:
      event: [ push ]

  # Deploy snapshot artifact to artifactory.
  mavenDeploySnapshot:
    image: meltwaterfoundation/drone-maven-jdk8
    pull: true
    secrets: [ artifactory_username, artifactory_password ]
    commands:
      - echo 'Deploy snapshot artifact to Artifactory.'
      - mvn -U clean deploy -s settings.xml
    when:
      event: [ push ]
      branch: [ master ]

  # Build test deploy release artifact to artifactory
  mavenDeployRelease:
    image: meltwaterfoundation/drone-maven-jdk8
    pull: true
    secrets: [ artifactory_username, artifactory_password, karma_robot_email, karma_robot_username, karma_github_token ]
    commands:
      - echo 'Release artifact to Artifactory'
      - mvn versions:set -DremoveSnapshot
      - mvn help:evaluate -Dexpression=project.version --quiet -Doutput=maven_artifact_version
      - export MAVEN_VERSION=$(eval cat maven_artifact_version)
      - rm maven_artifact_version
      - git config credential.helper 'cache --timeout=120'
      - git config user.email "$KARMA_ROBOT_EMAIL"
      - git config user.name "$KARMA_ROBOT_USERNAME"
      - git checkout release
      - git tag -a $MAVEN_VERSION release -m "Preparing release $MAVEN_VERSION"
      - git add pom.xml
      - git branch
      - git commit -m "Updating to release version $MAVEN_VERSION [CI SKIP]"
      - git push origin $MAVEN_VERSION
      - git push origin release
      - mvn -U clean deploy -s settings.xml -Dnlp.data.dir=nlp-data
      - echo 'Setting development version to next increment.'
      - git checkout dev
      - chmod +x incVer.sh
      - /bin/bash incVer.sh
      - mvn versions:commit
      - mvn push origin dev
    when:
      event: [ push ]
      branch: [ release ]

  slack:
    group: notifications
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    icon_url: https://logo.clearbit.com/drone.io
    username: 'Drone'
    channel: nlp-bots
    template: |
      {{#success build.status}}
        Build succeeded.
      {{else}}
        Build failed.
      {{/success}}
      Repo: `{{ repo.name }}`
      Branch: `{{ build.branch }}`
      Author: `{{ build.author }}`
      Commit: `{{ build.commit }}`
      Build: `{{ build.number }}`
    when:
      status: [ success, failure ]
      branch: [ master, release ]

  # Caching (create/refresh)
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./maven-repo
      - ./nlp-data
    volumes:
      - /tmp/cache:/cache
    when:
      event: [ push ]